[2024-02-29 14:33:04,094] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_redshift.crear_tabla_redshift scheduled__2022-09-15T03:00:00+00:00 [queued]>
[2024-02-29 14:33:04,113] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_redshift.crear_tabla_redshift scheduled__2022-09-15T03:00:00+00:00 [queued]>
[2024-02-29 14:33:04,114] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-02-29 14:33:04,115] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-02-29 14:33:04,116] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-02-29 14:33:04,161] {taskinstance.py:1397} INFO - Executing <Task(RedshiftSQLOperator): crear_tabla_redshift> on 2022-09-15 03:00:00+00:00
[2024-02-29 14:33:04,173] {standard_task_runner.py:52} INFO - Started process 527 to run task
[2024-02-29 14:33:04,181] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_con_conexion_redshift', 'crear_tabla_redshift', 'scheduled__2022-09-15T03:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres_database.py', '--cfg-path', '/tmp/tmp5je5iklm', '--error-file', '/tmp/tmp1hb4uqtb']
[2024-02-29 14:33:04,203] {standard_task_runner.py:80} INFO - Job 15: Subtask crear_tabla_redshift
[2024-02-29 14:33:04,295] {task_command.py:371} INFO - Running <TaskInstance: dag_con_conexion_redshift.crear_tabla_redshift scheduled__2022-09-15T03:00:00+00:00 [running]> on host 85ed7e7789a6
[2024-02-29 14:33:04,449] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Joaco
AIRFLOW_CTX_DAG_ID=dag_con_conexion_redshift
AIRFLOW_CTX_TASK_ID=crear_tabla_redshift
AIRFLOW_CTX_EXECUTION_DATE=2022-09-15T03:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-15T03:00:00+00:00
[2024-02-29 14:33:04,451] {redshift_sql.py:76} INFO - Executing statement: 
            create table if not exists fin_mundo(
                dt date,
                pais varchar(30)
            )
        
[2024-02-29 14:33:04,482] {base.py:68} INFO - Using connection ID 'redshift_keys' for task execution.
[2024-02-29 14:33:05,994] {dbapi.py:231} INFO - Running statement: 
            create table if not exists fin_mundo(
                dt date,
                pais varchar(30)
            )
        , parameters: None
[2024-02-29 14:33:06,704] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=dag_con_conexion_redshift, task_id=crear_tabla_redshift, execution_date=20220915T030000, start_date=20240229T143304, end_date=20240229T143306
[2024-02-29 14:33:06,853] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-29 14:33:07,104] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-29 21:09:45,227] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_redshift.crear_tabla_redshift scheduled__2022-09-15T03:00:00+00:00 [queued]>
[2024-02-29 21:09:45,268] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_redshift.crear_tabla_redshift scheduled__2022-09-15T03:00:00+00:00 [queued]>
[2024-02-29 21:09:45,269] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-02-29 21:09:45,271] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-02-29 21:09:45,272] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-02-29 21:09:45,324] {taskinstance.py:1397} INFO - Executing <Task(RedshiftSQLOperator): crear_tabla_redshift> on 2022-09-15 03:00:00+00:00
[2024-02-29 21:09:45,333] {standard_task_runner.py:52} INFO - Started process 425 to run task
[2024-02-29 21:09:45,342] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_con_conexion_redshift', 'crear_tabla_redshift', 'scheduled__2022-09-15T03:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres_database.py', '--cfg-path', '/tmp/tmp9wujs0je', '--error-file', '/tmp/tmpp8j0ehmq']
[2024-02-29 21:09:45,346] {standard_task_runner.py:80} INFO - Job 14: Subtask crear_tabla_redshift
[2024-02-29 21:09:45,520] {task_command.py:371} INFO - Running <TaskInstance: dag_con_conexion_redshift.crear_tabla_redshift scheduled__2022-09-15T03:00:00+00:00 [running]> on host 7b7d0ec4f6af
[2024-02-29 21:09:45,813] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Joaco
AIRFLOW_CTX_DAG_ID=dag_con_conexion_redshift
AIRFLOW_CTX_TASK_ID=crear_tabla_redshift
AIRFLOW_CTX_EXECUTION_DATE=2022-09-15T03:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-15T03:00:00+00:00
[2024-02-29 21:09:45,814] {redshift_sql.py:76} INFO - Executing statement: 
            create table if not exists fin_mundo(
                dt date,
                pais varchar(30)
            )
        
[2024-02-29 21:09:45,907] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/redshift_sql.py", line 78, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 204, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/redshift_sql.py", line 130, in get_conn
    conn_params = self._get_conn_params()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/redshift_sql.py", line 67, in _get_conn_params
    conn = self.conn
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/redshift_sql.py", line 63, in conn
    return self.get_connection(self.redshift_conn_id)  # type: ignore[attr-defined]
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `redshift_keys` isn't defined
[2024-02-29 21:09:45,912] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_con_conexion_redshift, task_id=crear_tabla_redshift, execution_date=20220915T030000, start_date=20240229T210945, end_date=20240229T210945
[2024-02-29 21:09:45,929] {standard_task_runner.py:97} ERROR - Failed to execute job 14 for task crear_tabla_redshift (The conn_id `redshift_keys` isn't defined; 425)
[2024-02-29 21:09:45,954] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-02-29 21:09:46,016] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
